### ISSUE TITLE
Duplicate call to /oauth20_token.srf

### ISSUE THREAD

**Issue by cgollner** [liveservices/LiveSDK-for-Android#43]
Shortly after log in is successful, and `onAuthComplete` is called, I get an `onAuthError`call. After taking a look into Fiddler, I could tell that a second call to **/oauth20_token.srf** was being made, using exactly the same parameters.
I looked into the live sdk code, but couldn't figure out where the problem was. I commented all the "after log in" code from my app, to make sure it wasn't something on my side. 
Take a look at the screen shots.

![First call](https://dl.dropboxusercontent.com/u/9699990/ScreenshotsPublic/Screenshot%202014-12-03%2013.33.27.png)

![Second call](https://dl.dropboxusercontent.com/u/9699990/ScreenshotsPublic/Screenshot%202014-12-03%2013.33.35.png)

**Comment by peternied** [comment]
Trying to start the new year off with a clean start, feel free to response if you can reproduce the issue and have a sample I can take a quick look at.
