### ISSUE TITLE
AuthorizationResult.onPageFinished(WebView view, String url) throws NullPointerException 

### ISSUE THREAD

**Issue by huangcd** [liveservices/LiveSDK-for-Android#50]
Step:
When login in, 
1. after user enter there name and password, in the confirm page (xxx app is requesting you permission ... YES, NO)
2. turn off the network.
3. Click YES or NO
after a while, the app will crash.

The `url` passed to `AuthorizationResult.onPageFinished` method is "data:text/html,chromewebdata", then `uri.getHost().equals(Config.INSTANCE.getOAuthLogoutUri().getHost())` will throw `NullPointerException`

For now, I can only reproduce this crash in XiaoMi phone

**Comment by bright-tools** [comment]
In my case, where network access is disabled before login is called, it seems that onPageFinished() is called twice, once with https://login.live.com/oauth20_authorise.srf?.... as the URL and the second time with data:text/html,chromewebdata as the URL.

url.getHost() returns null, which causes the NullPointerException.  Adding a check for this works for me:

    Uri uri = Uri.parse(url);
    String uriHost = uri.getHost();

    if( uriHost != null ) {
        // only clear cookies that are on the logout domain.
        if (uriHost.equals(Config.INSTANCE.getOAuthLogoutUri().getHost())) {
