### ISSUE TITLE
Maven/Gradle support

### ISSUE THREAD

**Issue by tprochazka** [liveservices/LiveSDK-for-Android#51]
Please upload jar to the maven central on jcenter repository.

**Comment by black-snow** [comment]
+1, I don't know how to use this w/ Android Studio

**Comment by camdenfullmer** [comment]
+1

**Comment by peternied** [comment]
We are putting our efforts into the new [OneDrive APIs](https://dev.onedrive.com), and are not looking to attract more attention to this older (Slower/Less Reliable/Less Time for Fixes) LiveSDKs.  I understand that it would be really handy to have this SDK available in a package, and be assured that when we do release an SDK for the new OneDrive APIs it will be avaliable through package mangement systems.

**Comment by huangcd** [comment]
Hi peter, does the new OneDrive API only works for OneDrive? Or it's able to use for generic OAuth
