### ISSUE TITLE
Add Docu/Tutorial/How-To/Wiki

### ISSUE THREAD

**Issue by black-snow** [liveservices/LiveSDK-for-Android#57]
The existing questions on SO barely help (me) using this SDK. Please add some solid documentation for the SDK.

**Comment by peternied** [comment]
Do you have a more specific question?

**Comment by black-snow** [comment]
Yes I do. Would you prefer a separate issue for each?

**Comment by peternied** [comment]
Actually, if you are looking at building a new application to connect to OneDrive, I would advise you use our replacement API for this library, https://dev.onedrive.com, it does not have an Android SDK available yet; however, we have a functional sample application that should cover most of your scenarios along with killer documentation.

**Comment by black-snow** [comment]
Okay, thanks
