### ISSUE TITLE
LiveSDK keep user info event if user decide not to grant access permission

### ISSUE THREAD

**Issue by huangcd** [liveservices/LiveSDK-for-Android#58]
Repro step:
1. Login with your account.
2. In the "Let this app access your info?" page, click "No".
3. Login Again.

Expect:
Ask me to login with my account and password first and then display the "Let this app access your info?" page

Actual:
Display the "Let this app access your info?" page directly.

**Comment by peternied** [comment]
This is the design of the login flow to prevent the users from being re-prompted to enter there information if we've got a valid cookie in the browser cache, as some applications will explicitly ask for permission every time they are called.

If you are looking to change this behavoir for your application you can try doing:

```java
@Override
public void onAuthError(LiveAuthException exception, Object userState) {
    showToast(exception.getMessage());
    CookieManager.getInstance().removeAllCookie(); // This will reset all stored cookie info so users must renter a username and password.
}
````

**Comment by huangcd** [comment]
Thank you @peternied, that solve my problem. Actually I agree with you that we should keep user logged in if they've already entered their credentials, but at least we should have an option to allow user to logout on the ask for permission page.
