### ISSUE TITLE
Does the new OneDrive API only works for OneDrive? Or it's able to use for generic OAuth

### ISSUE THREAD

**Issue by peternied** [liveservices/LiveSDK-for-Android#59]
Reposting for @huangcd

**Comment by peternied** [comment]
The new OneDrive API will not support scenarios like mail or calendar as it is just focused on giving you access to your files in the cloud.

To your second question about OAuth, the implementation of OAuth that ships with the OneDrive API SDKs will work with all Microsoft Account/Azure Active Directory accounts.  As to this implementation being portable for other OAuth services, I don't believe that is a goal.  When we have more details when those SDKs are available and you can try them out for yourself.

To get more information on the OneDrive APIs, make sure you watch https://github.com/OneDrive/onedrive-api-docs

**Comment by huangcd** [comment]
Thank you for the explanation
