### ISSUE TITLE
Can not cancel downloadAsync task.

### ISSUE THREAD

**Issue by pomelozero** [liveservices/LiveSDK-for-Android#60]
when I call LiveDownloadOperation downloadAsync(String path,File file,LiveDownloadOperationListener listener)  method to download a big file, then UI thread call cancel method, but the download task is still running, at last the onDownloadCompleted callback function will be called. my code as follows:

1. UI thread call start() method;
public void start(){
        try {
            File local = new File(mLocalFilePath);
            Helper.makeSureDocExist(local);
            mDownloadOperation = LiveSdkApplication.getSingleton(null).getConnectClient().downloadAsync(mOneDriveFilePath + "/content",
                    local, new LiveDownloadOperationListener() {
                        @Override
                        public void onDownloadProgress(int totalBytes,
                                                       int bytesRemaining,
                                                       LiveDownloadOperation operation) {
                            mCallback.onProgressUpdate((long)((totalBytes - bytesRemaining) / (float)totalBytes * 100));
                        }

                        @Override
                        public void onDownloadFailed(LiveOperationException exception,
                                                     LiveDownloadOperation operation) {
                            mErrorMsg = exception.getMessage();
                            mCallback.onFinishDownLoad(false, mLocalFilePath,mErrorMsg);
                        }

                        @Override
                        public void onDownloadCompleted(LiveDownloadOperation operation) {
                            mErrorMsg = "DownloadFile success!";
                            mCallback.onFinishDownLoad(true, mLocalFilePath,mErrorMsg);
                        }
                    });
        }catch (Exception e){
            Log.e(TAG, e.toString());
        }
    }

2.UI thread call mDownloadOperation.cancel();
3. after moment onDownloadCompleted will be called, and the big file still be downloaded.

**Comment by peternied** [comment]
While AsyncTask supports cancellation, as you've seen this is not actually supported by the LiveDownloadOperation.  While the underlying HttpClient that is used support this behavoir it is not plumbed through.

For this library we are not looking at making any feature enhancements at this time; however, we are open to pull requests from the community around this code base.
