### ISSUE TITLE
Google Play Warning: SSL Error Handler Vulnerability 

### ISSUE THREAD

**Issue by alexeyvasilyev** [liveservices/LiveSDK-for-Android#63]
This is what I have just received from Google.

The problem is in class AuthorizationWebViewClient method onReceivedSslError()
```
@Override
public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
    // TODO: Android does not like the SSL certificate we use, because it has '*' in
    // it. Proceed with the errors.
    handler.proceed();
}
```

Hello Google Play Developer,

Your app(s) listed at the end of this email have an unsafe implementation of the WebViewClient.onReceivedSslError handler. Specifically, the implementation ignores all SSL certificate validation errors, making your app vulnerable to man-in-the-middle attacks. An attacker could change the affected WebView's content, read transmitted data (such as login credentials), and execute code inside the app using JavaScript.

Please address this vulnerability as soon as possible and increment the version number of the upgraded APK. To properly handle SSL certificate validation, change your code to invoke SslErrorHandler.proceed() whenever the certificate presented by the server meets your expectations, and invoke SslErrorHandler.cancel() otherwise.

For more information about the SSL error handler, please see our documentation in the Android Developers Help Center. For other technical questions, you can post to https://www.stackoverflow.com/questions and use the tags “android-security” and “SslErrorHandler.”

To confirm you’ve upgraded correctly, submit the updated version to the Developer Console and check back after five hours. If the app hasn’t been correctly upgraded, we will display a warning.

While these specific issues may not affect every app that uses WebView SSL, it’s best to stay up to date on all security patches. Apps with vulnerabilities that expose users to risk of compromise may be considered dangerous products in violation of the Content Policy and section 4.4 of the Developer Distribution Agreement.

Apps must also comply with the Developer Distribution Agreement and Content Policy. If you have questions or concerns, please contact our support team through the Google Play Developer Help Center.

Regards,

The Google Play Team

**Comment by peternied** [comment]
@alexeyvasilyev I'm going to look at what is going on here, thanks for reporting.

**Comment by alexeyvasilyev** [comment]
Fix which works for me is just disable onReceivedSslError function defined in AuthorizationWebViewClient. In this case handler.cancel will be called in case of SSL error. However it works good with One Drive SSL certificates. Tested on Android 2.3.7, Android 5.1.

**Comment by peternied** [comment]
Yup, I think it might have been an testing artifact from a different set of SSL resources that were used, I'll have a pull request out on the minute

**Comment by JCEEDUBYOU** [comment]
I didn't send you this...
U didn't ask for your help and i don't use Android..,

Date: Fri, 25 Sep 2015 13:43:13 -0700

**Comment by praveen77321** [comment]
If i am not using any webView in my Game, i am using only 3rd party adsSDK
